version: "3.7"
services:
  postgres:
    container_name: prisma-accelerate-local-test-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - prisma-accelerate-local-test-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  prisma-accelerate-local-test-vol:
